page/urls.py
from django.conf.urls import  url
from . import views_page,views_site,views_editor


urlpatterns = [
     url(r'site/edit/$', views_site.Edit.as_view(),name='site_edit' ),

     url(r'add/upload/$', views_page.Upload_File.as_view(),name='page_add_upload' ),
     url(r'add/links/$', views_page.Edit_Links.as_view(),name='page_add_links' ),
     url(r'add/$', views_page.Add.as_view(),name='page_add' ),
     url(r'list/$', views_page.List.as_view(),name='page_list' ),
     url(r'(?P<slug>.*)/edit/links/$', views_page.Edit_Links.as_view(),name='page_edit_links' ),
     url(r'(?P<slug>.*)/edit/images/$', views_page.Edit_Images.as_view(),name='page_edit_images' ),
     url(r'(?P<slug>.*)/edit/editor/add$', views_editor.Add.as_view(),name='editor_add' ),
     url(r'(?P<slug>.*)/edit/editor/delete/(?P<editor>.*)/$', views_editor.Delete.as_view(),name='editor_delete' ),
     url(r'(?P<slug>.*)/edit/$', views_page.Edit.as_view(),name='page_edit' ),
     url(r'(?P<slug>.*)/delete/$', views_page.Delete.as_view(),name='page_delete' ),

]

page/models.py
import os
import datetime
import re

from django.db import models
from django.conf import settings
from django.core.cache import cache
import hashlib
from django.contrib.auth.models import User
from django.apps import apps
from django.utils import timezone
from django.core.exceptions import ObjectDoesNotExist


re_alphaplus = re.compile("[^a-zA-Z0-9/\.]")
re_page_slug = re.compile('^[\w\-_/]+$')

class Invalid_Page_Name(Exception):
    pass

PAGE_SITE = getattr(settings, 'PAGE_SITE', 'page.Site')
PAGE_PAGE = getattr(settings, 'PAGE_PAGE', 'page.Page')
PAGE_USER = getattr(settings, 'PAGE_USER', 'page.Page_User')
PAGE_CACHE_EXPIRE =getattr(settings, 'PAGE_CACHE_EXPIRE', 60*60*4 ) # four hour
PAGE_PAGE_CACHE= getattr(settings, 'PAGE_PAGE_CACHE', False) # disable page_cache by default
PAGE_SITE_CACHE= getattr(settings, 'PAGE_SITE_CACHE', False) # disable page_cache by default



def get_class_model_perm(class_model,perm):
    (model_class,model) = get_class_model(PAGE_PAGE)
    perm = "%s.%s_%s" %(model_class,perm,model)
    return perm.lower()
 
def get_class_model(class_model):
    return class_model.split('.')

#monkey patch user to show fullname  Subclassing breaks manytomany deletes
def user_unicode(self):
    return self.get_full_name()

User.__unicode__ = user_unicode 

#site
def get_page_site_key(domain_name):
    return "page_site/%s" % domain_name

def get_site_model():
    return apps.get_model ( *PAGE_SITE.split('.',1) )

def get_page_site(request):
    page_site = None
    if PAGE_SITE_CACHE:#try cache
        key = get_page_site_key(request.get_host())
        page_site = cache.get(key,None)

    if page_site:
        return page_site
    else:
        page_site_model = get_site_model()
        page_site = page_site_model.get_site(request)
        if PAGE_SITE_CACHE:
            cache.set(key,page_site,PAGE_CACHE_EXPIRE)
        return page_site

def get_page_site_version_key(domain_name):
    return "page_site_version/%s" % domain_name
   
def get_page_site_version(request):
    if PAGE_PAGE_CACHE:
        key = get_page_site_version_key(request.get_host())
        return cache.get(key,0)
    else:
        return 0

def invalidate_site_cache(request):
    if PAGE_PAGE_CACHE:
        domain_name = request.get_host()
        try:
            cache.incr(get_page_site_version_key(domain_name))
        except ValueError:
            cache.set(get_page_site_version_key(domain_name),1)

        cache.delete(get_page_site_key(domain_name))
        if (request.page_site):
            cache.delete(get_page_site_key(request.page_site.domain_name))

def get_page_site_user():
    page_user =  apps.get_model ( *PAGE_USER.split('.',1) )
    return page_user

#page
def get_page_model():
    return apps.get_model ( *PAGE_PAGE.split('.',1) )

def get_page(request):
    slug = request.path[1:].lower().rstrip('/')
    if slug == "":
        slug="default"

    page = None

    if PAGE_PAGE_CACHE:
        key = get_page_key(request.page_site.pk,slug)

        if not request.GET.get('refresh') :
            page = cache.get(key,None)

    if not page:
        try:
            #print "looking for page slug %s" % slug
            page_model =  get_page_model()

            page = page_model.objects.get(slug=slug,site=request.page_site)
            #print("looking for page page %s" % slug)
            if PAGE_PAGE_CACHE:
                cache.set(key,page,PAGE_CACHE_EXPIRE)
        except ObjectDoesNotExist:
            page = None 
                
    return page


def get_page_key(site_pk,slug):
    #print "get_page slug='%s'" % slug

    if re_page_slug.match(slug) is None:
        raise Invalid_Page_Name

    #use cache if there
    key = "%s/page/%s" % (site_pk,slug)
    #key = hashlib.md5(key).hexdigest()
    return key

    
class Site_Abstract(models.Model):
    class Meta:
        abstract = True
        
    title = models.CharField(max_length = 200)
    domain_name = models.CharField(max_length = 300,primary_key=True)
    default_domain = models.BooleanField(default=False)

    meta_data = models.TextField(blank=True,null=True)
    footer = models.TextField(blank=True,null=True)

    def __str__(self):
        return self.title

    @staticmethod
    def get_site(request):
        try:
            page_site = get_site_model().objects.get(domain_name = request.get_host())
        except ObjectDoesNotExist:
            try:
                page_site = get_site_model().objects.filter(default_domain = True)[0]
            except IndexError: #create the site
                page_site = get_site_model()(domain_name = request.get_host(),title=request.get_host())
                page_site.save()
        return page_site


if PAGE_SITE == 'page.Site':
    class Site(Site_Abstract):
        pass     
    
class Page_User(User):
    class Meta:
        proxy = True
        
    @staticmethod
    def get_site_users(site):
        """overide this model and supply this function to use custom users, for example, based on site"""
        return Page_User.objects.all()



class Page_Abstract(models.Model):
    class Meta:
        abstract = True
        permissions = (
            ("change_show_in_menu", "change_show_in_menu"),
        )

    site = models.ForeignKey(PAGE_SITE,on_delete=models.CASCADE)
    slug = models.CharField(max_length = 100,db_index=True)
    title = models.CharField(max_length = 100,verbose_name="Menu Title")
    show_in_menu = models.BooleanField(default=False)
    priority = models.IntegerField(default=0)
    html_title = models.CharField(max_length = 100,null=True,blank=True)
    content = models.TextField()
    members_only = models.BooleanField(default=False)
    lastmod = models.DateTimeField(default=timezone.now)
    sitemap  = models.BooleanField(default=True,verbose_name="Share a link to this page with search engines")


    def get_absolute_url(self):
        return "/%s" % self.slug

    def __str__(self):
        return self.slug

class Page_Editor(models.Model):
    page = models.ForeignKey(PAGE_PAGE,db_index=True,on_delete=models.CASCADE)
    editor = models.ForeignKey(PAGE_USER,db_index=True,on_delete=models.CASCADE)
    
    def __str__(self):
        return "%s %s" % (self.page,self.editor)

if PAGE_PAGE == 'page.Page':
    class Page(Page_Abstract):
        pass

class Page_Version(models.Model):
    page = models.ForeignKey(PAGE_PAGE,on_delete=models.CASCADE)
    saved = models.DateTimeField(default=timezone.now)
    data = models.TextField()
    class Meta:
        ordering = ["-saved"]


    def __str__(self):
        return "%s:%s %s" % (self.page.site,self.page.slug,self.saved)

def upload_uuid_file_to(instance,filename):
    path = 'page/%s' % instance.uuid
    return get_filename(path,filename,255)

class UUID_File(models.Model):
    file = models.FileField(max_length=255,upload_to=upload_uuid_file_to)
    uuid = models.CharField(max_length=100)

    def filename(self):
        return os.path.basename(self.file.name)
    
    def __str__(self):
        return self.file.name

def get_filename(path,filename,max_len):
    dst = '%s/%s' % (path,filename)
    if len(dst) > max_len:
        dst = '%s/%s' % (path,hashlib.md5(filename).hexdigest())

    return dst


def upload_file_to(instance,filename):
#    ext = os.path.splitext(filename)[1]
#    ext = ext.lower()
    path = 'page/%s' % instance.page.pk
    return get_filename(path,filename,255)

class File(models.Model):
    file = models.FileField(max_length=255,upload_to=upload_file_to)
    page = models.ForeignKey(PAGE_PAGE,related_name = 'page_file',on_delete=models.CASCADE)


    def filename(self):
        return os.path.basename(self.file.name)

    def __str__(self):
        return self.file.name

page/forms.py
from django.urls import reverse
from django.forms import ModelForm
import django.forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit,Field,Layout,ButtonHolder,Fieldset,HTML,Div,Hidden

from django.utils.encoding import smart_text
from django.core.exceptions import ValidationError
import re
from . import models

BUTTONS = Layout (
              ButtonHolder(
                Submit('submit', 'Save',css_id='save_button'),
                Submit('submit', 'Save and Close',css_id='save_close_button'),
                HTML('&#160;<a href="/{{object.slug}}" class="btn btn-danger" " >Close</a>')
                )
          )

slug_re = re.compile(r'^[-/\w]+$')
class Site(ModelForm):
    class Meta:
        model = models.get_site_model()
        exclude = ()
        
    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.render_unmentioned_fields=True
        self.helper.layout = Layout(
            Fieldset(
                     'Edit {{ object }}',
                     'title',
                     'domain_name',
                     'default_domain',
                     'meta_data',
                     'footer',
                     ),
           BUTTONS
        )
        super(Site, self).__init__(*args,**kwargs)

class Page_Abstract(ModelForm):
    file = django.forms.FileField(required=False)
    
    class Meta:
        model = models.get_page_model()
        fields = ['slug','title','members_only','content','html_title','sitemap']
        abstract=True
        
    def __init__(self, *args, **kwargs):
        self.site = kwargs.pop('site')
        super(Page_Abstract, self).__init__(*args,**kwargs)

        self.helper = FormHelper(self)
#        self.helper.form_class = 'form-horizontal'
#        self.helper.label_class = 'col-lg-2'
#        self.helper.field_class = 'col-lg-8'
        self.helper.form_id = 'page_edit_form'
        self.helper.attrs['novalidate'] = True

        self.page_options =Layout(
            Field(Hidden('uuid', '{{ uuid }}')),
            Fieldset(
                     'Edit {{ request.GET.slug}}',
                     'slug',
                     'title',
                     'html_title',
                     'members_only',
                     'sitemap'
                     )
                                 
                )
        self.file_layout = Layout (
                                   
                        Fieldset(
                         'Files',
                          'file',
                          HTML("{% include \"page/file_upload.html\" %}"),
                          
                          ),
                       )
        

        self.helper.layout = Layout(
                 self.page_options,
                 'content',
                 self.file_layout,
                HTML("<br />"),
               BUTTONS
        )
        
    def clean_slug(self):
        slug = self.cleaned_data['slug'].lower()

        if not slug_re.search(smart_text(slug)):
            raise ValidationError("Enter a valid 'slug' consisting of letters, numbers, underscores, slashes or hyphens.")

        slug = slug.rstrip('/')
        if slug != self.instance.slug and models.get_page_model().objects.filter(site=self.site,slug=slug).exists():
            raise ValidationError("Sorry that name is already taken")
        
        return slug

class Page(Page_Abstract):
    pass

class Page_Show_In_Menu(Page_Abstract):
    class Meta:
        model = models.get_page_model()
        fields = ['slug','title','members_only','priority','content','show_in_menu','html_title','sitemap']
        
    def __init__(self, *args, **kwargs):
        super(Page_Show_In_Menu, self).__init__(*args,**kwargs)
        self.helper.layout = Layout(
                 self.page_options,
                 'show_in_menu',
                 'priority',
                 'content',
                 self.file_layout,
                 HTML("<br />"),
                 BUTTONS 
        )

page/templates/page/editor_confirm_delete.html
{% extends 'desktop.html' %}

{% block content %}

Are you sure you want to delete:
<h1>{{ editor.user.get_full_name}}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="" method="post">
{% csrf_token %}
<input type="hidden" name="pk" value="{{editor.pk}}">
<input type="submit" value="Delete" />
</form>

{% endblock %}

page/templates/page/editor_form.html
{% extends 'desktop.html' %}

{% block content %}

<form method="post" class="form-inline">
{% csrf_token %}
  <fieldset>
    <legend>Add Page Editor</legend>
    <input name="username" type="text" placeholder="search by username">
    <input name="first_name" type="text" placeholder="search by firstname">
    <input name="last_name" type="text" placeholder="search by lastname">
    <button type="submit" class="btn">Search</button>
  </fieldset>
</form>

<ol>
	{% for editor in found_editors %}
		<li>
			{{editor.get_full_name}} ({{editor.username}})
			<form method="post" class="form-inline" style="display:inline;">
				{% csrf_token %}
				<input type="hidden" name="add_editor" value="{{editor.pk}}">
			    <button type="submit" class="btn">Add</button>
			</form>
		</li>
	{% endfor %}
</ol>
{% endblock %}

page/templates/page/file_upload.html
<!-- Force latest IE rendering engine or ChromeFrame if installed -->
<!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"><![endif]-->
<link rel="stylesheet" href="{{STATIC_URL}}page/uploader/css/style.css">
<link rel="stylesheet" href="{{STATIC_URL}}page/uploader/css/jquery.fileupload.css">

<div id="div_id_file_uploader" class="form-group">
	<label for="id_file_uploader" class="control-label ">Upload Files</label>
	<div class="controls ">
        <!-- The fileinput-button span is used to style the file input field as button -->
        <span class="btn btn-success fileinput-button">
            <i class="glyphicon glyphicon-plus"></i>
            <span>Add files...</span>
            <!-- The file input field used as target for the file upload widget -->
            <input id="fileupload" type="file" name="files[]" multiple>
        </span>
        <!-- The global progress bar -->
        <div id="progress" class="progress">
            <div class="progress-bar progress-bar-success"></div>
        </div>
        <!-- The container for the uploaded files -->
        <div id="files" class="files">
            {% for file in files %}
                <div>
                   <a href="{{file.file.url}}">{{file.filename}}</a> Remove:<input type="checkbox" name="remove_file" value="{{file.pk}}">
                </div>
            {% endfor %}
        </div>
	</div>
</div>


<script src="{{ STATIC_URL }}page/uploader/js/vendor/jquery.ui.widget.js"></script>
<!-- The Load Image plugin is included for the preview images and image resizing functionality -->
<script src="//blueimp.github.io/JavaScript-Load-Image/js/load-image.all.min.js"></script>
<!-- The Canvas to Blob plugin is included for image resizing functionality -->
<script src="//blueimp.github.io/JavaScript-Canvas-to-Blob/js/canvas-to-blob.min.js"></script>
<!-- The Iframe Transport is required for browsers without support for XHR file uploads -->
<script src="{{ STATIC_URL }}page/uploader/js/jquery.iframe-transport.js"></script>
<!-- The basic File Upload plugin -->
<script src="{{ STATIC_URL }}page/uploader/js/jquery.fileupload.js"></script>
<!-- The File Upload processing plugin -->
<script src="{{ STATIC_URL }}page/uploader/js/jquery.fileupload-process.js"></script>
<!-- The File Upload image preview & resize plugin -->
<script src="{{ STATIC_URL }}page/uploader/js/jquery.fileupload-image.js"></script>
<!-- The File Upload audio preview plugin -->
<script src="{{ STATIC_URL }}page/uploader/js/jquery.fileupload-audio.js"></script>
<!-- The File Upload video preview plugin -->
<script src="{{ STATIC_URL }}page/uploader/js/jquery.fileupload-video.js"></script>
<!-- The File Upload validation plugin -->
<script src="{{ STATIC_URL }}page/uploader/js/jquery.fileupload-validate.js"></script>
<script>
/*jslint unparam: true, regexp: true */
/*global window, $ */
$(function () {
    'use strict';
    $('#fileupload').fileupload({
        url: '{% url 'page_add_upload' %}',
        dataType: 'json',
        autoUpload: true,
        formData: [
                        { name: 'uuid', value: "{{uuid}}" },
                        { name: "csrfmiddlewaretoken", value: "{{ csrf_token }}"}
                    ],
//        acceptFileTypes: /(\.|\/)(gif|jpe?g|png)$/i,
        maxFileSize: 5000000, // 5 MB
        // Enable image resizing, except for Android and Opera,
        // which actually support image resizing, but fail to
        // send Blob objects via XHR requests:
        disableImageResize: /Android(?!.*Chrome)|Opera/
            .test(window.navigator.userAgent),
        previewMaxWidth: 100,
        previewMaxHeight: 100,
        previewCrop: true
    }).on('fileuploadadd', function (e, data) {
        data.context = $('<div/>').appendTo('#files');
        $('#progress .progress-bar').css('width',0);

        $.each(data.files, function (index, file) {
            var node = $('<span/>').text(file.name);
            node.appendTo(data.context);
        });
    }).on('fileuploadprocessalways', function (e, data) {
        var index = data.index,
            file = data.files[index],
            node = $(data.context.children()[index]);
        if (file.preview) {
            node
                .prepend('<br>')
                .prepend(file.preview);
        }
        if (file.error) {
            node
                .append('<br>')
                .append($('<span class="text-danger"/>').text(file.error));
        }
        if (index + 1 === data.files.length) {
            data.context.find('button')
                .text('Upload')
                .prop('disabled', !!data.files.error);
        }
    }).on('fileuploadprogressall', function (e, data) {
        var progress = parseInt(data.loaded / data.total * 100, 10);
        $('#progress .progress-bar').css(
            'width',
            progress + '%'
        );
    }).on('fileuploaddone', function (e, data) {
        $.each(data.result.files, function (index, file) {
            if (file.url) {
                var link = $('<a>')
                    .attr('target', '_blank')
                    .prop('href', file.url);
                $(data.context.children()[index])
                    .wrap(link);

                //$('<input />', { type: 'checkbox', id: 'cb', value: 'ham'}).appendTo($(data.context.children()[index]).find('div').first());
                $(data.context.children()[index]).parent().append('  Remove:<input type="checkbox" name="remove_new_file" value="' + file.pk + '">');
            } else if (file.error) {
                var error = $('<span class="text-danger"/>').text(file.error);
                $(data.context.children()[index])
                    .append('<br>')
                    .append(error);
            }
        });
    }).on('fileuploadfail', function (e, data) {
        $.each(data.files, function (index) {
            var error = $('<span class="text-danger"/>').text('File upload failed.');
            $(data.context.children()[index])
                .append('<br>')
                .append(error);
        });
    }).prop('disabled', !$.support.fileInput)
        .parent().addClass($.support.fileInput ? undefined : 'disabled');


    $('#div_id_file').remove();
});
</script>

page/templates/page/page_confirm_delete.html
{% extends 'desktop.html' %}

{% block content %}

Are you sure you want to delete:
<h1>{{ object}}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="" method="post">
{% csrf_token %}
{{form}}
<input type="submit" value="Delete" />
</form>

{% endblock %}

page/templates/page/page_detail.html
{% extends 'desktop.html' %}

{% block title %} {% if request.page.html_title %}{{ request.page.html_title }} {% else %}{{request.page_site.title}} {{request.page.title}}{% endif %} {% endblock %}
{% block content %}
{% if history %}
	<div class="row" id="history">
		<div class="col-md-12">
			<form>
				<input type="hidden" name="history" value="1">
				Version:<select name="version" onChange="submit();">
					{% for version_option in history %}
						<option value="{{version_option.pk}}" {% ifequal version.pk version_option.pk %} selected {% endifequal %} >{{version_option.saved}}</option>
					{% endfor %}
				</select>
				<input type="submit" value="View">
	
				{% if version %}
					{% if perms.page.change_page %}<a href="?history=1&revert=1&version={{version.pk}}&next=/{{page.slug}}">Revert to {{version.saved}} Version as shown below.</a>{% endif %} &nbsp;
				{% endif %}
			</form>
		<div>	
	</div>
	
{% endif %}
<div class="row">
    <div class="col-md-12">
    {% if object %}
        {% if user_page_edit %}
            <a class="btn btn-warning" href="{% url 'page_edit' object.slug %}" > Edit Page</a>
        {% endif %}
        {{object.content|safe}}
    {% else %}
                Sorry that page was not found.
                {% if user_page_add %}
                    <a href="{% url 'page_add' %}?slug={{slug}}" > Add Now</a>
                {% endif %}
    {% endif %}
    </div>
</div>


{% endblock %}

page/templates/page/page_form.html
{% extends 'desktop.html' %}


{% load crispy_forms_tags %}

{% block header %}

{% endblock %}
{% block title %} Page Edit {% endblock %}

{% block content %}
<script type="text/javascript" src="{{ STATIC_URL }}tinymce/js/tinymce/jquery.tinymce.min.js"></script>
<script type="text/javascript">

function endsWith(str, suffix) {
    return str.indexOf(suffix, str.length - suffix.length) !== -1;
}

    function onComplete(id,filename,response)
{
    if (endsWith(filename.toLowerCase(),'jpg'))
	  $('#id_content').tinymce().execCommand('mceInsertContent',false,'<img src="' + response.url +  '">');
    else if (endsWith(filename.toLowerCase(),'gif'))
	  $('#id_content').tinymce().execCommand('mceInsertContent',false,'<img src="' + response.url +  '">');
    else if (endsWith(filename.toLowerCase(),'jpeg'))
	  $('#id_content').tinymce().execCommand('mceInsertContent',false,'<img src="' + response.url +  '">');
    else
	  $('#id_content').tinymce().execCommand('mceInsertContent',false,'<br /><a href="' + response.url +  '">' + filename + '</a>');

}
        $(function() {
                $('#id_content').tinymce({
                        // Location of TinyMCE script
                        script_url : '{{ STATIC_URL }}tinymce/js/tinymce/tinymce.min.js',
                         //width:"100%",
                         height:"600px",
                         extended_valid_elements : "script[type|src],iframe[src|style|width|height|scrolling|marginwidth|marginheight|frameborder]",
                         valid_children : "+body[style]" ,
                         preformatted : true,
                         removed_menuitems: 'newdocument',
                         apply_source_formatting : true,
                        // General options
						theme : "modern",
						plugins : "{{PAGE_TINYMCE_PLUGINS}},table,preview,media,searchreplace,paste,fullscreen,noneditable,visualchars,nonbreaking,link,image,code,autolink",
                        noneditable_leave_contenteditable: true,

					// Drop lists for link/image/media/template dialogs
		//			template_external_list_url : "/lists/template_list.js",
					link_list : "links?uuid={{uuid}}",
					image_list : "images?uuid={{uuid}}",
					//media_external_list_url : external_link_list_url,
					relative_urls : false,
			         noneditable_leave_contenteditable : true,
                    toolbar1  : 'undo redo | bold italic underline | ' +
                    'alignleft aligncenter alignright alignjustify  | ' +
                    'bullist numlist | outdent indent |  blockquote removeformat | link image| news feeds'

                });

        });

</script>
   <a href="/{{object.slug}}?history=1">History</a>
{% crispy form %}
<br />
{% if perms.page.delete_page %}
    <br />
	<a class="btn btn-danger" href="{% url 'page_delete' object.slug %}" > Delete Page</a>
{% endif %}

  <h2>Page Editors</h2>
	<ol>
		{% for editor in editors %}
			<li>
				{{editor.editor.get_full_name}} ({{editor.editor.username}})
				{% if perms.page.delete_editor_page %}
					<a class="btn btn-danger" href="{% url 'editor_delete' object.slug editor.pk %}" > Delete </a>
				{% endif %}
			</li>
		{% endfor %}
		{% if perms.page.add_editor_page %}
			<li><a class="btn btn-primary"  href="{% url 'editor_add' object.slug %}">Add</a></li>
		{% endif %}
	</ol>



{% endblock %}

page/templates/page/page_list.html
{% extends 'desktop.html' %}

{% block header %}
{% endblock %}
      
{% block title %}Page{% endblock %}

{% block content %}
<h1>Page</h1>
<div class="container">
<table class="table table-striped table-bordered table-hover table-responsive table-nonfluid" >

{% for item in page_list %}
    <tr>
        <td >
            <a href="/{{item.slug}}">{{item.slug}}</a>
        </td>
        <td>
            {% if perms.page.change_page %}<a class="btn btn-warning" href="{% url 'page_edit' item.slug %}"> <span class="glyphicon glyphicon-edit"> Edit</a>{% endif %}
        <td>
            {% if perms.page.delete_page %}
                <a class="btn btn-danger" href="{% url 'page_delete' item.slug %}"> <span class="glyphicon glyphicon-remove"> Delete </a>
            {% endif %}
        </td>

        </td>
    </tr>

{% endfor %}

{% if perms.churchnest_page.add_page %}
    <tr><td class="text-center" colspan="3">
        <a class="btn btn-primary" href="{% url 'page_add' %}" > <span class="glyphicon glyphicon-plus "></span>  Add </a>
    </td> </tr>
{% endif %}

</table>
</div>

{% endblock %}

page/templates/page/rss.html
{% for entry in feed %}
    {% if feed|length > 1 %}
        <div class="rss_item well">
    {% endif %}
<a href="{{ entry.link }}" target="rss">
    {{ entry.title }}
</a>
{% if not headers_only %}
    <div class="rss_description">{% if max_words %}{{ entry.description|safe|truncatewords_html:max_words }}{% else %}
        {{ entry.description|safe }}{% endif %}</div>
{% endif %}
{% if feed|length > 1 %}
    </div>
{% endif %}
{% endfor %}

page/templates/page/site_form.html
{% extends 'desktop.html' %}

{% load crispy_forms_tags %}

{% block content %}
<a class="btn btn-info" href="{% url 'page_list' %}">Page List</a>
{% crispy form %}

{% endblock %}